### ISSUE TITLE
Can't get inner collection

### ISSUE THREAD

**Issue by M9nood** [morrislaptop/firestore-php#10]
**Can't get inner collection**
structure : collection/document/innercollection/innerdocument
i want to get data form inner document but i can't use
$firestore->colloection('collection')->document('document')->collection('innerCollection')->document('innerDocument')

**Comment by putrasurya** [comment]
it's working like this
$firestore->collection("collection/document/innerCollection")->document("innerDocument");

**Comment by M9nood** [comment]
thank you very much. :)
