### ISSUE TITLE
Code not working (v2.1.2)

### ISSUE THREAD

**Issue by rohit1290** [morrislaptop/firestore-php#3]
Which one is the correct code??
```
collection = self::$firestore->getCollection('users');
$user = $collection->getDocument('123456');
```
or

```
collection = $firestore->collection('users');
$user = $collection->document('123456');
```
I cannot find getCollection or getDocument function in any of the class.

The second code is working for me but I am getting a new error 
PHP Fatal error:  Uncaught Error: Class 'Morrislaptop\\Firestore\\PermissionDenied' not found

**Comment by morrislaptop** [comment]
I've added the PermissionDenied class, but there will still be a problem with your auth credentials if it's getting to that bit of the code.

**Comment by rohit1290** [comment]
what about the first part of the question? Which one is the correct code??

**Comment by morrislaptop** [comment]
Second one.
