### ISSUE TITLE
DocumentReference has no methods id(), name() or path()

### ISSUE THREAD

**Issue by KgotsoK** [morrislaptop/firestore-php#5]
Hi 

I keep trying to access the `DocumentSnapshot::id()` method but I realised that it uses the its contained DocumentReference instance to get the id like so:

```   
public function id()
    {
        return $this->reference->id();
    }

```

The `id()` method doesn't exist in the `DocumentReference` class so this call throws an exception. I also noticed that the `DocumentSnapshot::name()` and the `DocumentSnapshot::path()` methods also use the `name()` and the `path` methods on the `DocumentReference` instance which also don't exist.

**Comment by KgotsoK** [comment]
Hey @morrislaptop How do we get the document ID in that case?

**Comment by alexmgillis** [comment]
I try to get the id by accessing the path however i got this error when trying to access to it:
"Morrislaptop\Firestore\DocumentReference::$uri"
My workaround takes patching the source code : 
file:  src\DocumentReference.php
line: 22 (class DocumentReference)
- Private $uri;
+ Public $uri;
 
Example:
        //init firestore 
        $firestore=...
        $collection = $firestore->collection("your/collection/path");
        $collectionArray=[];
        $iterator=$collection->documents()->getIterator();
        while ($iterator->valid()) {
            $document=$iterator->current();
           //now uri is public so i can get path using a getter 
           $path = explode('/',  $document->reference()->uri->getPath());
            $id = end($path);
             $collectionArray[$id]=$document->data();
            $iterator->next();
        }
It works but it feels i am missing something
is any reason why uri is private?
Is any other way to access to uri w/o patching the code?
Is this an acceptable solution and should i propose a pull?
perhaps add  id() in DocumentSnapshot.php?
       public function id()
    {
        if( !$this->exists || $this->reference==null) return null;
        $path = explode('/',  $this->reference->uri->getPath());
        return (end($path));
    }

**Comment by morrislaptop** [comment]
PR would be great - supposed to mirror the API of  https://googleapis.github.io/google-cloud-php/#/docs/cloud-firestore/v1.6.2/firestore/documentreference?method=path

**Comment by alexmgillis** [comment]
i'll check it out and send an pr soon.
