### ISSUE TITLE
How to return more than 20 documents when accessing a collection?

### ISSUE THREAD

**Issue by pjhartin** [morrislaptop/firestore-php#6]
When looping over each document after calling `$collection->documents()`, I only ever get 20 records back.
Is it possible to increase the number of documents returned from the `$collection->documents()` method or implement an interator?

```
$collection = $firestore->collection('food-entries');
/** @var DocumentSnapshot $document */
$collection->documents();
foreach ($collection->documents() as $document) {
    $data = $document->data();
}
```

**Comment by pjhartin** [comment]
@morrislaptop - Thanks for addressing this mate. Very much appreciated.

**Comment by zeevx** [comment]
It is still returning 20 documents only, please help!
